### PR TITLE
GCI-ing imports

### PR DESCRIPTION
**Pull request by AnomalRoil**
Running gci in order to make sure we have properly deterministic imports with a nice and consistent formatting.

See: https://github.com/daixiang0/gci

### CODE REVIEW

**Comment by AnomalRoil** [comment]
I'll rebase, I wanted to work without having to install go 1.18 beta 1, but I see I won't be able to do that without having conflicts and annoying merge commits.

**Comment by dominikschulz** [comment]
Looks good. Can you please add it to our Makefile as well?
Either as a check in the `codequality` target, as a fix in the `fmt` target or both. As you prefer.

Thank you!

**Comment by AnomalRoil** [comment]
Yes, this is actually part of my new ongoing effort to migrate from our current Makefile codequality check to a more streamlined golangci-lint based one, which integrates nicely with Github :) 
More PRs to come soon.

**Review by dominikschulz — APPROVED** [review]
LGTM

**Pull request merged**
