### PR TITLE
Add dependabot.yml

### PR DESCRIPTION
**Pull request by n3ph**
Let's use GitHub's dependabot to check for GitHub Actions and GoLang dependencies

RELEASE_NOTES=n/a

Signed-off-by: Michael Gerlach <n3ph@cccfr.de>

### CODE REVIEW

**Comment by n3ph** [comment]
Fixes https://github.com/gopasspw/gopass/issues/1765

**Comment by n3ph** [comment]
Sorry for the noise. First I haven't had a look at the contribution guideline and messed up the signoff afterwards.. -,-

**Review by AnomalRoil — CHANGES_REQUESTED** [review]
Could you maybe add this option:
`open-pull-requests-limit: 5`
Just to make sure it's not too noisy at the beginning.

And please use `git commit --amend` and `git push --force` to avoid opening too many PRs ;)

**Comment by n3ph** [comment]
> And please use `git commit --amend` and `git push --force` to avoid opening too many PRs ;)
force pushing does not lead to re-run the test base. But I didn't tried to re-run them manually....

There are some other useful options too: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

I guess `rebase-strategy` is one which might be needed?

**Review by dominikschulz — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
