### PR TITLE
Add missing spaces after punctuation

### PR DESCRIPTION
**Pull request by avorima**

### CODE REVIEW

**Review by AnomalRoil — APPROVED** [review]

**Comment by dominikschulz** [comment]
@AnomalRoil I didn't merge this because it's useless. It will be overridden with the next release.

We need to fix the source.

**Comment by AnomalRoil** [comment]
Ah, I didn't know we were auto-generating the man-page.

**Comment by avorima** [comment]
Sorry, I didn't know either. Should I open a PR with the changes to the code?

**Comment by dominikschulz** [comment]
Oh, my bad. I notice it but didn't get to leave a note on this PR before @AnomalRoil did merge it.

No worries, it's still useful for me to track down the misspellings!

**Pull request merged**
