### PR TITLE
Add chezmoi to list of integrations

### PR DESCRIPTION
**Pull request by twpayne**

### CODE REVIEW

**Review by AnomalRoil — APPROVED** [review]
LGTM. 
You might want to add the code fences like the other tools, if it's a cmd line tool.

**Review by dominikschulz — APPROVED** [review]
LGTM

**Comment by twpayne** [comment]
> You might want to add the code fences like the other tools, if it's a cmd line tool.

Ah, I've just worked out what this means. In the case of chezmoi, I make a distinction between chezmoi the software, and `chezmoi` the command you run. A similar distinction exists between Go the programming language and `go` the tool you often use when developing software in Go. I'll happily add code fences if you want, but in the case of chezmoi, the non-code-fenced version is more correct.

**Comment by AnomalRoil** [comment]
Perfect then :)

**Pull request merged**
