### PR TITLE
Adding postrel GHA

### PR DESCRIPTION
**Pull request by AnomalRoil**
Adding a post-release GHA

This is a WIP, to be refined because the current post-release helper isn't working without a specific folder structure

### CODE REVIEW

**Comment by dominikschulz** [comment]
Do you have any idea how the folder structure should change?

**Comment by AnomalRoil** [comment]
I was thinking that we have really two options:

- one GHA here that would be pulling all the right repo in one folder and then we can have the folder structure as it is currently, or tweak it as we see fit
- create a new "post-release packaging" repo that would have all other repo we need as submodules and trigger a GHA there upon completion of our release GHA here, and then we should use that folder structure in our post-release helper.

What would you prefer ?

**Comment by dominikschulz** [comment]
@AnomalRoil Do you have plans to continue working on this?

I don't see how this could possibly work right now.
But feel free to prove me wrong.

**Comment by AnomalRoil** [comment]
I'd love to have a fully automated release process, but I think this isn't the right approach. Instead we should have a GHA running on tags that does all the rest.

**Pull request closed without merging**
