### PR TITLE
Updated clipboard vendor to add wayland support

### PR DESCRIPTION
**Pull request by r0l1**
`gopass -c` was broken on wayland. By updating the clipboard vendor package, this issue is solved.
I would appreciate, if you could increment the minor release version and publish a new release, so that this get's fixed upstream by the major linux distributions. Thanks!

### CODE REVIEW

**Comment by dominikschulz** [comment]
Thanks! Will try to do a new release soon.

**Comment by colemickens** [comment]
Ping for a release, please and thank you!

**Comment by dominikschulz** [comment]
Done

**Comment by sevenmaxis** [comment]
Seems to me it's back again. `--clip` option doesn't work

**Pull request merged**
