### PR TITLE
fix syntax in example for gopass config

### PR DESCRIPTION
**Pull request by DO1JLR**
my shell tells me that this must be called ``gopass config autosync=true``.

### CODE REVIEW

**Comment by dominikschulz** [comment]
This depends on your shell (which one?).
For me the documented syntax seems to work.

**Comment by DO1JLR** [comment]
I tested it with ``/bin/bash`` under Archlinux and ``cmd.exe`` in windows 10.

```bash
 $  gopass config autosync true

Error: Error setting config value
 $
 $
```
*(it's not working or what am I doing wrong?)*

```bash
 $  gopass config autosync=true
 $
 $
```
*(works now perfectly fine)*

----

Look at it via [asciinema](https://asciinema.org):
```
asciinema play https://github.com/gopasspw/gopass/files/5685762/gopasserror.cast.txt
```

[gopasserror.cast.txt](https://github.com/gopasspw/gopass/files/5685762/gopasserror.cast.txt)

**Comment by AnomalRoil** [comment]
I just tried and it seems that on my side the syntax with `=` is non-working.

**Comment by DO1JLR** [comment]
> I just tried and it seems that on my side the syntax with `=` is non-working.

Can you maybe give me a hint what I might be doing wrong?

I really made the pull request in the belief that I had found an inconsistency in the documentation by accident.

**Review by mniak — CHANGES_REQUESTED** [review]
The syntax `gopass config autosync=false` is wrong. It does not print an error just because gopass interprets `autosync=false` as the key, and as the value is not set for this key, it does not print anything.

This  PR should be rejected.

**Comment by DO1JLR** [comment]
ok, my bad. please excuse the disturbance. i just wanted to help!

**Pull request closed without merging**
