### PR TITLE
Use different concurrency groups for different workflows

### PR DESCRIPTION
**Pull request by dominikschulz**
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency

RELEASE_NOTES=n/a

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

**Comment by AnomalRoil** [comment]
TIL, nice I should do that on my own projects too 😄

**Comment by dominikschulz** [comment]
Not sure if that was clear, but this did lead to workflows "randomly" being canceled for no obvious reason.
That was very confusing until I found this.

Now they seem to work as expected.

**Comment by AnomalRoil** [comment]
Yeah, I guess the issue was that both the Grype and the build one had `-build` at the end.

You need unique concurrency names across workflows. Another option could have been to rename the Grype one with `-grype`.

**Comment by dominikschulz** [comment]
That was my first attempt. Until I saw this here mentioned in the docs. So I went with the best practice.

**Pull request merged**
