### PR TITLE
Replace chzyer/readline with ergochat/readline

### PR DESCRIPTION
**Pull request by dominikschulz**
The former seemed unmaintained and was lacking patches required for OpenBSD.

See GH-2683.

Some small changes were necessary since the ergochat fork changed the API a bit.

### CODE REVIEW

**Review by AnomalRoil — DISMISSED** [review]
LGTM

**Comment by jrick** [comment]
The REPL is working well for me with this on OpenBSD.

**Comment by dominikschulz** [comment]
The problem is that the `clear` command will be broken on Windows since ergochat/readline doesn't expose a `ClearScreen` method: https://github.com/ergochat/readline/issues/36

Not sure if we wan't to merge it was is.

**Review by AnomalRoil — APPROVED** [review]
LGTM. You'll need to rebase to sign-off the last commit of just merge as is without satisfying the DCO.

**Comment by dominikschulz** [comment]
The code looks good, but I want to quickly tests it before merging. Should be done soon and then we should try to cut a release.

**Pull request merged**
