### PR TITLE
Add suffix f to formating out methods

### LINKED ISSUE #1793: Problem with passwords containing characters matching fmt format specifiers
### Summary

I have a couple of passwords that have character groups matching the fmt package format specifiers. 
As an example there's `%3U`, which when using go show appears as `!U(MISSING)`.

This problem has appeared with version 1.12.0

### Steps To Reproduce

Create a password containing a string matching a fmt format specifier.

When showing the password with gopass it will be treated as a format specifier that's missing its value.

### Expected behavior

The password should be shown as is.

### Environment

- OS: Linux - Archlinux
- OS version: `Linux myhostname 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux`
- gopass Version: 
```
gopass 1.12.0 (2021-02-11 21:15:26) go1.15.8 linux amd64
<root>     - gpg 2.2.27 - git 2.30.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```
- Installation method: From Archlinux's community repository

### PR DESCRIPTION
**Pull request by dominikschulz**
This commit renames the existing out methods that expect
a format string to include the common f suffix and introduces
new out methods without this suffix that don't accept a
format string or variadic arguments.

Note: Everything outside of `internal/out/` is based on a
search and replace operation and doesn't need much
attention.

Fixes #1793

RELEASE_NOTES=n/a

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

**Review by AnomalRoil — APPROVED** [review]
Welp, we should have had a test case for this, I never thought it could happen. Would you mind adding a test for show with a password that would trigger this bug?

**Comment by dominikschulz** [comment]
Yes, I've added that. And had to fix some unrelated issues as well (e.g. one of the parsing disabled tests did actually expect the wrong output).

**Review by AnomalRoil — APPROVED** [review]
Perfect

**Comment by AnomalRoil** [comment]
Can you solve the conflict and merge?

**Comment by dominikschulz** [comment]
Done

**Pull request merged**
