### PR TITLE
Use callback for printing update progress

### PR DESCRIPTION
**Pull request by dominikschulz**
RELEASE_NOTES=n/a

Signed-off-by: Dominik Schulz <dominik.schulz@gauner.org>

### CODE REVIEW

**Review by AnomalRoil — DISMISSED** [review]
Not sure it really increases readability or maintainability though.

**Comment by dominikschulz** [comment]
Yes, sorry. Should have provided more context.
This was a first test to see if #1798 would be feasible.
Not sure if we should do that, but I wanted to give it a first try in a location where it doesn't hurt.

**Review by AnomalRoil — APPROVED** [review]
LGTM, but it's still in draft mode, why?

**Comment by dominikschulz** [comment]
You have some concerns if this increases readability and I wanted to give it some more thought.

**Comment by dominikschulz** [comment]
This doesn't seem to help. Closing.

**Pull request closed without merging**
